name: secure_strings
description: "A tool for encrypting strings with XOR encryption."
resolution: workspace
version: 1.1.2
# If you plan to publish to pub.dev, add your repository/homepage
# repository: https://github.com/DowranRowshenow/secure_strings

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  # Required to read the user's pubspec configuration and package name
  yaml: ^3.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^6.0.0

# This section is CRUCIAL.
# It allows users to run 'dart run secure_strings' from their terminal.
executables:
  secure_strings: secure_strings
