name: secure_localizations_example
description: Test project for the encryption tool
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # This links the example to the package code in the folder above
  secure_localizations:
    path: ../

# Tool configuration
secure_localizations:
  # Optional: The command used to generate localizations.
  # Default is 'gen-l10n'
  # command: "pub run flutter_localizations_tk:gen_l10n_tk"

  # Optional: Where your ARB files are located.
  # arb_dir: "lib/l10n"

  # Optional: Where the generated Dart files and helper class should live.
  # output_dir: "lib/l10n"

flutter:
  generate: true
